#!/bin/bash

echo "Ensure that the previous execution has been closed."
echo "If you see 'kill: (xxxPIDxxx): No such process,' it means the previous execution has been closed."
/home/yen0224/NTUST/q

echo "***** Assigning IP addresses *****"
INTERFACE=$(ip route | grep default | sed -e "s/^.*dev.//" -e "s/.proto.*//")
INTERFACE="$(echo -e "${INTERFACE}" | tr -d '[:space:]')"

# Clear state
sudo ifconfig $INTERFACE:RIC_STUB down
sudo ifconfig $INTERFACE:CU_STUB down
sudo ifconfig $INTERFACE:ODU down
sudo ifconfig $INTERFACE:OAI_CU down
sudo ifconfig lo:RIC_STUB down
sudo ifconfig lo:CU_STUB  down
sudo ifconfig lo:ODU  down
sudo ifconfig lo:OAI_CU down

sudo ifconfig $INTERFACE:RIC_STUB "192.168.130.80"
sudo ifconfig $INTERFACE:ODU  "192.168.130.81"
sudo ifconfig $INTERFACE:CU_STUB "192.168.130.82"
sudo ifconfig $INTERFACE:OAI_CU "192.168.130.83"

sudo ifconfig lo:RIC_STUB "192.168.130.80"
sudo ifconfig lo:ODU  "192.168.130.81"
sudo ifconfig lo:OAI_CU "192.168.130.83"

PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:~/home/gnb/
export PATH
echo  "O-RAN NIC Setting Complete!"

sudo echo "Build OSC DU..."

cd /home/yen0224/new/small_cell_integration/l2/build/odu
#clean
make clean_odu MACHINE=BIT64 MODE=FDD NFAPI=YES
make clean_cu MACHINE=BIT64 MODE=FDD NFAPI=YES
make clean_ric MACHINE=BIT64 MODE=FDD NFAPI=YES

#compile
make odu MACHINE=BIT64 MODE=FDD NFAPI=YES
make cu_stub NODE=TEST_STUB MACHINE=BIT64 MODE=FDD NFAPI=YES
make ric_stub NODE=TEST_STUB MACHINE=BIT64 MODE=FDD NFAPI=YES

L2_PATH="/home/yen0224/new/small_cell_integration/l2"
LOG_PATH="/home/yen0224/NTUST/LOG"
CU_STUB_PATH="$L2_PATH/bin/cu_stub/cu_stub"
CU_LOG_FILE="$LOG_PATH/1-CU_STUB.log"
RIC_STUB_PATH="$L2_PATH/bin/ric_stub/ric_stub"
RIC_LOG_FILE="$LOG_PATH/2-RIC_STUB.log"
ODU_PATH="$L2_PATH/bin/odu/odu"
ODU_LOG_FILE="$LOG_PATH/3-OSC_DU.log"
PNF_PATH="/home/yen0224/openairinterface5g/cmake_targets/ran_build/build/nr-softmodem"
PNF_CONF="/home/yen0224/new/small_cell_integration/l2/mwnl/oai_pnf_conf/oaiL1.nfapi.usrpb210.conf"
PNF_LOG_FILE="$LOG_PATH/4-OAI_PNF.log"
PID_FILE="$LOG_PATH/PID_FILE_NAME"

cd ~

echo "RUN OSC CU_STUB"
sudo stdbuf -oL $CU_STUB_PATH 2>&1 | ts &>$CU_LOG_FILE &
sleep 2
CU_PID=$(pgrep -o cu_stub)
echo $CU_PID
echo -n $CU_PID > $PID_FILE
echo -n " " >> $PID_FILE

echo "RUN OSC RIC_STUB"
sudo stdbuf -oL $RIC_STUB_PATH 2>&1 | ts &>$RIC_LOG_FILE &
sleep 2
RIC_PID=$(pgrep -o ric_stub)
echo $RIC_PID
echo -n $RIC_PID >> $PID_FILE
echo -n " " >> $PID_FILE

echo "RUN OSC DU"
sudo stdbuf -oL $ODU_PATH 2>&1 | ts &>$ODU_LOG_FILE &
sleep 5
ODU_PID=$(pgrep -o odu)
echo $ODU_PID
echo -n $ODU_PID >> $PID_FILE
echo -n " " >> $PID_FILE

echo "RUN OAI PNF"
sudo stdbuf -oL $PNF_PATH -O $PNF_CONF --sa -E --gNBs.[0].min_rxtxtime 6 --continuous-tx --nfapi PNF 2>&1 | ts &>$PNF_LOG_FILE &
sleep 5
PNF_PID=$(pgrep -o nr-softmodem)
# $(pgrep -o -f "$PNF_PATH")
echo $PNF_PID
echo -n $PNF_PID >> $PID_FILE
