#!/bin/bash
sudo echo "Build OAI DU"

cd /home/yen0224/NTUST/openairinterface5g-NTUST/cmake_targets

sudo echo "Build OAI DU - step1"
# compile all of the code
./build_oai --gNB --nrUE -w SIMU

sudo echo "Build OAI DU - step2"
# sync up the format of F1AP
./f1ap_codec_mod.sh

sudo echo "Build OAI DU - step3"
# compile the part of RAN
cd /home/yen0224/NTUST/openairinterface5g-NTUST/cmake_targets
./build_oai --gNB