#!/bin/bash
sudo echo "Build OAI CU"

cd /home/hpe/bmwlab_tony_cu_du/oai_cu/cmake_targets
sudo echo "Build OAI CU - step1"
# compile all of the code
./build_oai --gNB --nrUE -w SIMU

sudo echo "Build OAI CU- step2"
# sync up the format of F1AP
./f1ap_codec_mod.sh

sudo echo "Build OAI CU - step3"
# compile the part of RAN
cd /home/hpe/bmwlab_tony_cu_du/oai_cu/cmake_targets
./build_oai --gNB