#!/bin/bash
source ./VARIABLE.sh
sudo echo ""
pids=$(ps aux | grep "odu\|ric_stub\|nr-uesoftmodem\|nr-softmodem\|ping 192.168.70.135 -I oaitun_ue1" | grep -v grep | awk '{print $2}')
# sudo pkill -INT tcpdump
for pid in $pids; do
    sudo kill -9 "$pid" > /dev/null 2>&1 &  # SIGTERM
    # echo "kill $pid"
done

LOCKFILE=$PATH_TO_SCRIPT/tmp-build_run.lock
cd "$(dirname "$0")"
if [ -e $LOCKFILE ]; then
    rm $LOCKFILE
fi

cd $PATH_TO_SCRIPT/Tools
bash "$PATH_TO_SCRIPT/Tools/q"