#!/bin/bash
sudo echo "Build OAI DU"

cd /home/hpe/openairinterface5g/cmake_targets

#compile
# ./build_oai -I -c -C
# ./build_oai -w USRP --gNB
#################### 2024/3/3 add for run in RFsim
sudo ./build_oai -c --ninja --nrUE --gNB
#################### 2024/3/3 add for run in RFsim

# bash "/home/hpe/NTUST-script/00"