HOME_DIR=$(eval echo ~$USER)
export PATH_TO_SCRIPT="$HOME_DIR/NTUST-script"
export PATH_TO_CU="$HOME_DIR/O-CU"
export PATH_TO_O_DU_L2="$HOME_DIR/OSC-DU-High/l2"
export PATH_TO_L1="$HOME_DIR/OAI_L1"
export PATH_TO_UE="$HOME_DIR/OAI_UE"
