ROOT_PATH="hpe"
export PATH_TO_SCRIPT="/home/$ROOT_PATH/NTUST-script"
export PATH_TO_CU="/home/$ROOT_PATH/bmwlab_tony_cu_du"
export PATH_TO_O_DU_L2="/home/$ROOT_PATH/mwnl-odu-at-oai-based-on-scf/l2"
export PATH_TO_L1_RFSIM_UE="/home/$ROOT_PATH/openairinterface5g"
