#!/bin/bash

# 進入目錄
cd /home/yen0224/NTUST/openairinterface5g/cmake_targets

# 第一個腳本
sudo ./build_oai -c --ninja --nrUE --gNB

# 進入目錄
cd /home/yen0224/NTUST/openairinterface5g/cmake_targets/ran_build/build

# 定義路徑變數
NFAPI_TRACE_LEVEL=info
LD_LIBRARY_PATH=.
CONF_PATH=../../../targets/PROJECTS/GENERIC-LTE-EPC/CONF
LOG_PATH=/home/yen0224/NTUST/LOG/nfapi-fixes

# 第二個腳本
sudo stdbuf -oL ./nr-softmodem -O $CONF_PATH/oaiL1.nfapi.usrpb210.conf --nfapi PNF --rfsim --rfsimulator.serveraddr server --sa 2>&1 | ts &> $LOG_PATH/PNF.log &

# 將PID寫入檔案
echo $! > /home/yen0224/NTUST/LOG/pids.txt

# 第三個腳本
sudo stdbuf -oL ./nr-softmodem -O $CONF_PATH/rcc.band78.tm1.106PRB.nfapi.conf --nfapi VNF --sa 2>&1 | ts &> $LOG_PATH/VNF.log &

# 將PID寫入檔案
echo $! >> /home/yen0224/NTUST/LOG/pids.txt
