#!/bin/bash

cd /home/yen0224/NTUST/openairinterface5g/cmake_targets/ran_build/build

# 定義路徑變數
NFAPI_TRACE_LEVEL=info
ASAN_OPTIONS=detect_leaks=0
LD_LIBRARY_PATH=.
CONF_PATH=../../../targets/PROJECTS/GENERIC-LTE-EPC/CONF
LOG_PATH=/home/yen0224/NTUST/nfapi-fixes/LOG

# 執行指令碼
sudo stdbuf -oL ./nr-softmodem -O $CONF_PATH/rcc.band78.tm1.106PRB.nfapi.conf --nfapi VNF --sa 2>&1 | ts &> $LOG_PATH/VNF-nfapi-fixes.log
