#!/bin/bash
source ../VARIABLE.sh

cd $PATH_TO_L1_RFSIM_UE/cmake_targets
# sudo ./build_oai -c --ninja --nrUE --gNB --sanitize
sudo ./build_oai -c --ninja --nrUE --gNB
## IF execute first time in your PC you need to add `-I`