#!/bin/bash
source ../VARIABLE.sh

L2_PATH=$PATH_TO_O_DU_L2
echo "L2_PATH=$L2_PATH"
# OSC root
OSC_build_PATH="$L2_PATH/build/odu"
# clean & compile OSC RIC
cd $OSC_build_PATH
make clean_ric NODE=TEST_STUB MACHINE=BIT64 MODE=TDD
make ric_stub NODE=TEST_STUB MACHINE=BIT64 MODE=TDD

# clean & compile OSC DU
#cd /home/hpe/o-du-l2/build/odu
cd $OSC_build_PATH
make clean_odu MACHINE=BIT64 MODE=TDD NFAPI=YES
make odu MACHINE=BIT64 MODE=TDD NFAPI=YES
