#!/bin/bash
source ../VARIABLE.sh

cd $PATH_TO_L1_UE/cmake_targets
# sudo ./build_oai -c --ninja --nrUE --gNB --sanitize
sudo ./build_oai -c --ninja --nrUE --gNB

# FH
sudo ./build_oai --gNB --ninja -t oran_fhlib_5g --cmake-opt -Dxran_LOCATION=/home/oai72_su/oai_mp_e/phy/fhi_lib/lib

## IF execute first time in your PC you need to add `-I`