#!/bin/bash

DIR_NAME="$1"
TARGET_DIR="/home/hpe/o-du-l2/src/codec_utils/$DIR_NAME"
CCOMMON_DIR="/home/hpe/o-du-l2/src/codec_utils/common"

for file in "$TARGET_DIR"/*; do
    if ! head -n 2 "$file" | grep -q 'Generated by asn1c-' && [[ "$file" == *.c || "$file" == *.h ]]; then
        sudo mv "$file" "$CCOMMON_DIR/"
        echo "Moved $(basename "$file") to common directory"
    fi
done