#!/bin/bash
source ../VARIABLE.sh

cd $PATH_TO_L1_UE/cmake_targets/ran_build/build
sudo ./nr-uesoftmodem -r 106 --numerology 1 --band 78 -C 3619200000 --uicc0.imsi 001010000000001 --rfsim 
# sudo ./nr-uesoftmodem -C 3619200000 -r 106 --numerology 1 --ssb 516 --band 78 --uicc0.imsi 001010000000001 --rfsim