#!/bin/bash

# To increase RFsim performance (follow PNF-LOG prompt)
sudo /sbin/sysctl -n -e -q -w net.core.rmem_default=134217728
sudo /sbin/sysctl -n -e -q -w net.core.rmem_max=134217728
sudo /sbin/sysctl -n -e -q -w net.core.wmem_default=134217728
sudo /sbin/sysctl -n -e -q -w net.core.wmem_max=134217728

# edit network interface
sudo ifconfig lo:RIC_STUB down
sudo ifconfig lo:CU_STUB  down
sudo ifconfig lo:ODU  down
sudo ifconfig lo:OAI_CU down
sudo ifconfig lo:local_n_address  down
sudo ifconfig lo:remote_n_address down
# sudo ifconfig lo:local_n_address  "127.0.0.1"
# sudo ifconfig lo:remote_n_address "127.0.0.2"

# follow from https://github.com/oai-group/openairinterface5g/blob/master/doc/RUN_NR_NFAPI.md#bring-up-another-loopback-interface
sudo ifconfig lo: 127.0.0.2 netmask 255.0.0.0 up

# Common path
Target_PATH="/home/yen0224/NTUST/nfapi-fixes"
LOG_PATH="$Target_PATH/LOG"
OAI_PATH="$Target_PATH/openairinterface5g/cmake_targets"

# 進入目錄
cd "$OAI_PATH"

# 第一個腳本
sudo ./build_oai -c --ninja --nrUE --gNB
# sudo ./build_oai --gNB --nrUE
# exit

# 進入目錄
cd "$OAI_PATH/ran_build/build"

sudo echo "Start TCPdump..."
sudo tcpdump -i any -nn -w $LOG_PATH/nFAPI_TCPdump.pcap &
# sudo tcpdump -i any -nn -w /home/yen0224/NTUST/nfapi-fixes/LOG/nFAPI_TCPdump.pcap &

# 定義路徑變數
NFAPI_TRACE_LEVEL=debug
LD_LIBRARY_PATH=.
CONF_PATH=../../../targets/PROJECTS/GENERIC-LTE-EPC/CONF

# Common part of nrsoftmodem_command
common_cmd="./nr-softmodem"

# Second script
pnf_cmd="$common_cmd -O $CONF_PATH/oaiL1.nfapi.usrpb210.conf --nfapi PNF --rfsim --rfsimulator.serveraddr server --sa"
sudo stdbuf -oL $pnf_cmd 2>&1 | ts &> "$LOG_PATH/PNF-nfapi-fixes.log" &

# Third script
sudo ASAN_OPTIONS=detect_leaks=0 
vnf_cmd="$common_cmd -O $CONF_PATH/rcc.band78.tm1.106PRB.nfapi.conf --nfapi VNF --sa"
sudo stdbuf -oL $vnf_cmd 2>&1 | ts &> "$LOG_PATH/VNF-nfapi-fixes.log" &

wait_sec=15
echo "The script automatically closes after $wait_sec seconds..."

# Wait for the specified number of seconds
sleep $wait_sec

bash "$Target_PATH/exit"

echo "Time to $wait_sec seconds..."

# /home/yen0224/NTUST/nfapi-fixes/openairinterface5g/targets/PROJECTS/GENERIC-LTE-EPC/CONF/oaiL1.nfapi.usrpb210.conf
# /home/yen0224/NTUST/nfapi-fixes/openairinterface5g/targets/PROJECTS/GENERIC-LTE-EPC/CONF/rcc.band78.tm1.106PRB.nfapi.conf
